apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
{{ toYaml .Values.resources | indent 12 }}
