model_name: gpt2

tokenizer:
  use_fast: true

policy:
  trust_remote_code: false

data:
  path: data/sft.jsonl
  split: train
  max_length: 512
  add_bos: true
  prompt_field: prompt
  response_field: response

training:
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 1
  num_train_epochs: 3
  learning_rate: 5e-5
  weight_decay: 0.0
  warmup_steps: 0
  lr_scheduler_type: linear
  logging_steps: 10
  save_strategy: steps
  save_steps: 200
  save_total_limit: 3
  evaluation_strategy: "no"
  fp16: true
  dataloader_num_workers: 2
  gradient_checkpointing: false
  torch_compile: false
  report_to: []